repos:
  - repo: local
    hooks:
      - id: gen-g-stubs
        name: Generate G stubs (api/__init__.pyi)
        entry: python -m scripts.gen_g_stubs
        language: system
        env:
          PYTHONPATH: .
        pass_filenames: false
      - id: test-g-stub-sync
        name: Test G stub sync
        entry: python -m pytest -q tests/test_g_stub_sync.py
        language: system
        env:
          PYTHONPATH: .
        pass_filenames: false
      - id: test-pipeline-stub-sync
        name: Test pipeline stub sync
        entry: python -m pytest -q tests/test_pipeline_stub_sync.py
        language: system
        env:
          PYTHONPATH: .
        pass_filenames: false
