# This file is auto-generated by tools/gen_g_stubs.py. DO NOT EDIT.
# Regenerate with: python -m tools.gen_g_stubs

from typing import Any, Protocol, TypedDict, TypeAlias
from engine.core.geometry import Geometry as Geometry
from api.effects import Pipeline as Pipeline

JSONScalar: TypeAlias = int | float | str | bool | None
JSONLike: TypeAlias = JSONScalar | list['JSONLike'] | dict[str, 'JSONLike']

class PipelineSpecStep(TypedDict):
    name: str
    params: dict[str, JSONLike]

PipelineSpec: TypeAlias = list[PipelineSpecStep]

class _GShapes(Protocol):
    def asemic_glyph(self, *, region: tuple[float, float, float, float] = ..., smoothing_radius: float = ..., diacritic_probability: float = ..., diacritic_radius: float = ..., random_seed: float = ..., **_params: Any) -> Geometry:
        ...
    def attractor(self, *, attractor_type: str = ..., points: int = ..., dt: float = ..., scale: float = ..., **_params: Any) -> Geometry:
        ...
    def capsule(self, *, radius: float = ..., height: float = ..., segments: int = ..., latitude_segments: int = ..., **_params: Any) -> Geometry:
        ...
    def cone(self, *, radius: float = ..., height: float = ..., segments: int = ..., **_params: Any) -> Geometry:
        ...
    def cylinder(self, *, radius: float = ..., height: float = ..., segments: int = ..., **_params: Any) -> Geometry:
        ...
    def grid(self, *, subdivisions: tuple[float, float] = ..., **_params: Any) -> Geometry:
        ...
    def lissajous(self, *, freq_x: float = ..., freq_y: float = ..., freq_z: float = ..., phase: float = ..., phase_y: float = ..., phase_z: float = ..., points: int = ..., **_params: Any) -> Geometry:
        ...
    def polygon(self, *, n_sides: int | float = ..., **_params: Any) -> Geometry:
        ...
    def polyhedron(self, *, polygon_type: Union[str, int, NoneType] = ..., polygon_index: int = ..., **_params: Any) -> Geometry:
        ...
    def sphere(self, *, subdivisions: float = ..., sphere_type: float = ..., **_params: Any) -> Geometry:
        ...
    def text(self, *, text: str = ..., font_size: float = ..., font: str = ..., font_number: int = ..., align: str = ..., **_params: Any) -> Geometry:
        ...
    def torus(self, *, major_radius: float = ..., minor_radius: float = ..., major_segments: int = ..., minor_segments: int = ..., **_params: Any) -> Geometry:
        ...
    def empty(self) -> Geometry: ...
    def from_lines(self, lines: Any) -> Geometry: ...

from common.types import Vec3

class _PipelineBuilder(Protocol):
    # meta: pivot (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    # meta: angles_rad (type=vec3, range=[(-3.141592653589793, -3.141592653589793, -3.141592653589793), (3.141592653589793, 3.141592653589793, 3.141592653589793)])
    # meta: scale (type=vec3, range=[(0.1, 0.1, 0.1), (3.0, 3.0, 3.0)])
    def affine(self, *, pivot: Vec3 | None = ..., angles_rad: Vec3 = ..., scale: Vec3 = ..., **_params: Any) -> _PipelineBuilder:
        """
        任意の変換（スケール→回転→移動）を適用する純関数エフェクト。

        引数:
            pivot: vec3, range [(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)]
            angles_rad: vec3, range [(-3.141592653589793, -3.141592653589793, -3.141592653589793), (3.141592653589793, 3.141592653589793, 3.141592653589793)]
            scale: vec3, range [(0.1, 0.1, 0.1), (3.0, 3.0, 3.0)]
        """
        ...
    # meta: intensity (type=number, range=[0.0, 10.0])
    # meta: subdivisions (type=integer, range=[0, 10])
    def collapse(self, *, intensity: float = ..., subdivisions: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        線分を細分化してノイズで変形（純関数）。

        引数:
            intensity: number, range [0.0, 10.0]
            subdivisions: integer, range [0, 10]
        """
        ...
    # meta: dash_length (type=number, range=[0.0, 100.0])
    # meta: gap_length (type=number, range=[0.0, 100.0])
    def dash(self, *, dash_length: float = ..., gap_length: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        連続線を破線に変換（純関数）。

        引数:
            dash_length: number, range [0.0, 100.0]
            gap_length: number, range [0.0, 100.0]
        """
        ...
    # meta: amplitude_mm (type=number, range=[0.0, 50.0])
    # meta: spatial_freq (type=number, range=[(0.0, 0.0, 0.0), (0.1, 0.1, 0.1)])
    # meta: t_sec (type=number, range=[0.0, 60.0])
    def displace(self, *, amplitude_mm: float = ..., spatial_freq: float | tuple[float, float, float] = ..., t_sec: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        3次元頂点にPerlinノイズを追加（クリーンAPI）。

        引数:
            amplitude_mm: number, range [0.0, 50.0]
            spatial_freq: number, range [(0.0, 0.0, 0.0), (0.1, 0.1, 0.1)]
            t_sec: number, range [0.0, 60.0]
        """
        ...
    # meta: factor (type=number, range=[0.0, 50.0])
    def explode(self, *, factor: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        中心から外側へ頂点を放射状に移動させるエフェクト。

        引数:
            factor: 移動距離（mm 単位）
        """
        ...
    # meta: direction (type=vec3)
    # meta: distance (type=number, range=[0.0, 200.0])
    # meta: scale (type=number, range=[0.0, 3.0])
    # meta: subdivisions (type=integer, range=[0, 5])
    # meta: center_mode (type=string)
    # choices: center_mode in ['origin', 'auto']
    def extrude(self, *, direction: Vec3 = ..., distance: float = ..., scale: float = ..., subdivisions: float = ..., center_mode: str = ..., **_params: Any) -> _PipelineBuilder:
        """
        2D/3Dポリラインを指定方向に押し出し、側面エッジを生成（純関数）。

        引数:
            direction: vec3
            distance: number, range [0.0, 200.0]
            scale: number, range [0.0, 3.0]
            subdivisions: integer, range [0, 5]
            center_mode: string, choices { 'origin', 'auto' }
        """
        ...
    # meta: mode (type=string)
    # choices: mode in ['lines', 'cross', 'dots']
    # meta: angle_rad (type=number, range=[0.0, 6.283185307179586])
    # meta: density (type=number, range=[0.0, 100])
    def fill(self, *, mode: str = ..., angle_rad: float = ..., density: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        閉じた形状をハッチング/ドットで塗りつぶし（純関数）。

        引数:
            mode: string, choices { 'lines', 'cross', 'dots' }
            angle_rad: number, range [0.0, 6.283185307179586]
            density: number, range [0.0, 100]
        """
        ...
    # meta: join (type=string)
    # choices: join in ['mitre', 'round', 'bevel']
    # meta: segments_per_circle (type=integer, range=[1, 1000])
    # meta: distance (type=number, range=[0.0, 25.0])
    # meta: distance_mm (type=number, min=0.0)
    def offset(self, *, join: str = ..., segments_per_circle: int = ..., distance: float = ..., distance_mm: float | None = ..., **_params: Any) -> _PipelineBuilder:
        """
        Shapely を使用したバッファ/オフセット（純関数）。

        引数:
            join: string, choices { 'mitre', 'round', 'bevel' }
            segments_per_circle: integer, range [1, 1000]
            distance: number, range [0.0, 25.0]
            distance_mm: number, min 0.0
        """
        ...
    # meta: count (type=integer, range=[0, 10])
    # meta: offset (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    # meta: angles_rad_step (type=vec3, range=[(-3.141592653589793, -3.141592653589793, -3.141592653589793), (3.141592653589793, 3.141592653589793, 3.141592653589793)])
    # meta: scale (type=vec3, range=[(0.1, 0.1, 0.1), (3.0, 3.0, 3.0)])
    # meta: pivot (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    def repeat(self, *, count: int = ..., offset: Vec3 = ..., angles_rad_step: Vec3 = ..., scale: Vec3 = ..., pivot: Vec3 = ..., **_params: Any) -> _PipelineBuilder:
        """
        入力のコピーを配列状に生成（純関数）。

        引数:
            count: integer, range [0, 10]
            offset: vec3, range [(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)]
            angles_rad_step: vec3, range [(-3.141592653589793, -3.141592653589793, -3.141592653589793), (3.141592653589793, 3.141592653589793, 3.141592653589793)]
            scale: vec3, range [(0.1, 0.1, 0.1), (3.0, 3.0, 3.0)]
            pivot: vec3, range [(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)]
        """
        ...
    # meta: amplitude (type=number, range=[0.0, 20.0])
    # meta: frequency (type=number, range=[(0.0, 0.0, 0.0), (0.2, 0.2, 0.2)])
    # meta: phase (type=number, range=[0.0, 6.283185307179586])
    def ripple(self, *, amplitude: float = ..., frequency: float | tuple[float, float, float] = ..., phase: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        座標値に基づくサイン波ゆらぎ（ウォブル）を各軸に適用する純関数エフェクト。

        引数:
            amplitude: 変位の大きさ（座標単位, mm 相当）
            frequency: 空間周波数 [cycles per unit]
            phase: 位相オフセット（ラジアン）
        """
        ...
    # meta: pivot (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    # meta: angles_rad (type=vec3, range=[(-3.141592653589793, -3.141592653589793, -3.141592653589793), (3.141592653589793, 3.141592653589793, 3.141592653589793)])
    def rotate(self, *, pivot: Vec3 = ..., angles_rad: Vec3 = ..., **_params: Any) -> _PipelineBuilder:
        """
        回転（新形式のみ）。

        引数:
            pivot: 回転の中心
            angles_rad: (rx, ry, rz) ラジアン角
        """
        ...
    # meta: pivot (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    # meta: scale (type=vec3, range=[(0.1, 0.1, 0.1), (5.0, 5.0, 5.0)])
    def scale(self, *, pivot: Vec3 = ..., scale: Vec3 = ..., **_params: Any) -> _PipelineBuilder:
        """
        スケール変換を適用（純関数）。

        引数:
            pivot: スケーリングの中心（`(x, y, z)`）
            scale: 各軸の倍率（`(sx, sy, sz)`）
        """
        ...
    # meta: subdivisions (type=integer, range=[0, 10])
    def subdivide(self, *, subdivisions: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        中間点を追加して線を細分化（純関数）。

        引数:
            subdivisions: integer, range [0, 10]
        """
        ...
    # meta: delta (type=vec3, range=[(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)])
    def translate(self, *, delta: Vec3 = ..., **_params: Any) -> _PipelineBuilder:
        """
        指定ベクトルで平行移動（Geometry メソッドに委譲）。

        引数:
            delta: vec3, range [(-300.0, -300.0, -300.0), (300.0, 300.0, 300.0)]
        """
        ...
    # meta: start_param (type=number, range=[0.0, 1.0])
    # meta: end_param (type=number, range=[0.0, 1.0])
    def trim(self, *, start_param: float = ..., end_param: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        ポリラインの一部区間だけを残すトリム処理（純関数）。

        引数:
            start_param: 開始位置（0.0–1.0）
            end_param: 終了位置（0.0–1.0）
        """
        ...
    # meta: angle (type=number, range=[0.0, 360.0])
    # meta: axis (type=string)
    # choices: axis in ['x', 'y', 'z']
    def twist(self, *, angle: float = ..., axis: str = ..., **_params: Any) -> _PipelineBuilder:
        """
        位置に応じて軸回りにねじるエフェクト（角度は度）。

        引数:
            angle: 最大ねじれ角（度）
            axis: ねじれ軸（"x"|"y"|"z"）
        """
        ...
    # meta: num_candidate_lines (type=integer, range=[0, 500])
    # meta: relaxation_iterations (type=integer, range=[0, 50])
    # meta: step (type=number, range=[0.0, 0.5])
    def weave(self, *, num_candidate_lines: float = ..., relaxation_iterations: float = ..., step: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        形状にウェブ状のストリング構造を追加（純関数）。

        引数:
            num_candidate_lines: integer, range [0, 500]
            relaxation_iterations: integer, range [0, 50]
            step: number, range [0.0, 0.5]
        """
        ...
    # meta: amplitude (type=number, range=[0.0, 20.0])
    # meta: frequency (type=number, range=[(0.0, 0.0, 0.0), (0.2, 0.2, 0.2)])
    # meta: phase (type=number, range=[0.0, 6.283185307179586])
    def wobble(self, *, amplitude: float = ..., frequency: float | tuple[float, float, float] = ..., phase: float = ..., **_params: Any) -> _PipelineBuilder:
        """
        線にウォブル/波の歪みを追加（純関数）。

        引数:
            amplitude: 変位量（座標単位, mm 相当）
            frequency: 空間周波数 [cycles per unit]
            phase: 位相（ラジアン）
        """
        ...
    def build(self) -> Pipeline: ...
    def strict(self, enabled: bool = ...) -> _PipelineBuilder: ...
    def cache(self, *, maxsize: int | None) -> _PipelineBuilder: ...
    def __call__(self, g: Geometry) -> Geometry: ...

class _Effects(Protocol):
    @property
    def pipeline(self) -> _PipelineBuilder: ...

from .shapes import ShapesAPI as ShapesAPI

G: _GShapes
E: _Effects
from shapes.registry import shape as shape
from effects.registry import effect as effect
from .sketch import run_sketch as run_sketch, run_sketch as run
def to_spec(pipeline: Pipeline) -> PipelineSpec: ...
def from_spec(spec: PipelineSpec) -> Pipeline: ...
def validate_spec(spec: PipelineSpec) -> None: ...

__all__ = [
    'G', 'E', 'shape', 'effect', 'run_sketch', 'run', 'ShapesAPI', 'Geometry', 'to_spec', 'from_spec', 'validate_spec',
]
