name: Verify G Stubs

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy fonttools pytest
      - name: Generate stubs
        run: python -m scripts.gen_g_stubs
      - name: Ensure stubs are up-to-date
        run: |
          git diff --exit-code api/__init__.pyi || (echo 'api/__init__.pyi is outdated; run python -m scripts.gen_g_stubs' && exit 1)
      - name: Run stub sync test
        run: pytest -q tests/test_g_stub_sync.py -q
      - name: Run pipeline stub sync test
        run: pytest -q tests/test_pipeline_stub_sync.py -q
