name: Verify & Test

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Cache pytest
        uses: actions/cache@v4
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pytest-
      - name: Generate stubs
        env:
          PYTHONPATH: src
        run: python -m scripts.gen_g_stubs
      - name: Ensure stubs are up-to-date
        run: |
          git diff --exit-code api/__init__.pyi || (echo 'api/__init__.pyi is outdated; run python -m scripts.gen_g_stubs' && exit 1)
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (black --check)
        run: black --check . --extend-exclude "^api/__init__\\.pyi$"
      - name: Imports (isort --check-only)
        run: isort --check-only .
      - name: Type check (mypy)
        run: mypy
      - name: Run tests (unit/integration/e2e/perf)
        run: pytest -q -m "not optional"
  optional-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install optional deps
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core
          python -m pip install --upgrade pip
          pip install -e .[dev,optional]
      - name: Run optional tests
        env:
          TEST_FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
        run: pytest -q -m optional
